final List<Map<String, dynamic>> menuItemsData = [

  {
    'id': 'item_gobi_65',
    'name': 'Gobi 65',
    'description': 'Crispy cauliflower tossed in spicy masala',
    'categoryId': 'cat_appetizers',
    'price': 40.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_spring_roll',
    'name': 'Spring Roll',
    'description': 'Crispy vegetable filled rolls',
    'categoryId': 'cat_appetizers',
    'price': 50.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_shanghai_roll',
    'name': 'Shanghai Roll',
    'description': 'Special shanghai style roll',
    'categoryId': 'cat_appetizers',
    'price': 60.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_paneer_tikka',
    'name': 'Paneer Tikka',
    'description': 'Grilled cottage cheese with spices',
    'categoryId': 'cat_appetizers',
    'price': 70.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_chilly_paneer',
    'name': 'Chilly Paneer',
    'description': 'Paneer tossed in spicy chilly sauce',
    'categoryId': 'cat_appetizers',
    'price': 70.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_pasta',
    'name': 'Pasth=a',
    'description': 'Indian style pasta dish',
    'categoryId': 'cat_main_appetizers',
    'price': 45.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_pasta_mix',
    'name': 'Pasta Mix',
    'description': 'Mixed pasta varieties with special sauce',
    'categoryId': 'cat_main_appetizers',
    'price': 55.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_veg_biryani',
    'name': 'Veg Biryani',
    'description': 'Fragrant rice with mixed vegetables',
    'categoryId': 'cat_rice',
    'price': 80.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_fried_rice',
    'name': 'Fried Rice',
    'description': 'Stir-fried rice with vegetables',
    'categoryId': 'cat_rice',
    'price': 35.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_schezwan_rice',
    'name': 'Schezwan Rice',
    'description': 'Rice tossed in spicy schezwan sauce',
    'categoryId': 'cat_rice',
    'price': 40.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_noodles',
    'name': 'Noodles',
    'description': 'Stir-fried noodles with vegetables',
    'categoryId': 'cat_noodles',
    'price': 35.0,
    'inStock': true,
    'imageUrl': '',
  },{
    'id': 'item_samosa',
    'name': 'Samosa',
    'description': 'Crispy pastry filled with spiced potatoes',
    'categoryId': 'cat_appetizers',
    'price': 10.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_puff',
    'name': 'Puff',
    'description': 'Flaky pastry with savory filling',
    'categoryId': 'cat_appetizers',
    'price': 10.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_meals',
    'name': 'Meals',
    'description': 'Complete meal with rice, curry and sides',
    'categoryId': 'cat_rice',
    'price': 35.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_mix_fried_rice',
    'name': 'Mix Fried Rice',
    'description': 'Fried rice with mixed vegetables',
    'categoryId': 'cat_rice',
    'price': 50.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_paneer_fried_rice',
    'name': 'Paneer Fried Rice',
    'description': 'Fried rice with paneer pieces',
    'categoryId': 'cat_rice',
    'price': 55.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_paneer_mix_fried_rice',
    'name': 'Paneer Mix Fried Rice',
    'description': 'Fried rice with paneer and mixed vegetables',
    'categoryId': 'cat_rice',
    'price': 60.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_schezwan_rice_mix',
    'name': 'Schezwan Rice Mix',
    'description': 'Spicy schezwan rice with mixed vegetables',
    'categoryId': 'cat_rice',
    'price': 50.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_jeera_rice',
    'name': 'Jeera Rice',
    'description': 'Rice flavored with cumin seeds',
    'categoryId': 'cat_rice',
    'price': 35.0,
    'inStock': true,
    'imageUrl': '',
  },


  {
    'id': 'item_veg_biryani',
    'name': 'Veg Biryani',
    'description': 'Fragrant rice with mixed vegetables',
    'categoryId': 'cat_rice',
    'price': 80.0,
    'inStock': true,
    'imageUrl': '',
  },

  // Noodles
  {
    'id': 'item_noodles',
    'name': 'Noodles',
    'description': 'Plain stir-fried noodles',
    'categoryId': 'cat_noodles',
    'price': 35.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_noodles_mix',
    'name': 'Noodles Mix',
    'description': 'Stir-fried noodles with mixed vegetables',
    'categoryId': 'cat_noodles',
    'price': 50.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_paneer_noodles',
    'name': 'Paneer Noodles',
    'description': 'Stir-fried noodles with paneer',
    'categoryId': 'cat_noodles',
    'price': 55.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_schezwan_noodles',
    'name': 'Schezwan Noodles',
    'description': 'Spicy schezwan flavored noodles',
    'categoryId': 'cat_noodles',
    'price': 40.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_schezwan_noodles_mix',
    'name': 'Schezwan Noodles Mix',
    'description': 'Spicy schezwan noodles with mixed vegetables',
    'categoryId': 'cat_noodles',
    'price': 50.0,
    'inStock': true,
    'imageUrl': '',
  },

  // Main Course
  {
    'id': 'item_pastha',
    'name': 'Pastha',
    'description': 'Indian style pasta dish',
    'categoryId': 'cat_appetizers',
    'price': 45.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_pastha_mix',
    'name': 'Pastha Mix',
    'description': 'Mixed pasta varieties with special sauce',
    'categoryId': 'cat_appetizers',
    'price': 55.0,
    'inStock': true,
    'imageUrl': '',
  },

  // Beverages
  {
    'id': 'item_sprite',
    'name': 'Sprite',
    'description': 'Refreshing lemon-lime soft drink',
    'categoryId': 'cat_beverages',
    'price': 20.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_mountain_dew',
    'name': 'Mountain Dew',
    'description': 'Citrus-flavored soft drink',
    'categoryId': 'cat_beverages',
    'price': 20.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_thumbsup',
    'name': 'Thumbs Up',
    'description': 'Strong cola flavor soft drink',
    'categoryId': 'cat_beverages',
    'price': 20.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_pepsi',
    'name': 'Pepsi',
    'description': 'Classic cola soft drink',
    'categoryId': 'cat_beverages',
    'price': 20.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_fanta',
    'name': 'Fanta',
    'description': 'Orange flavored soft drink',
    'categoryId': 'cat_beverages',
    'price': 20.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_limca',
    'name': 'Limca',
    'description': 'Lemon-lime flavored soft drink',
    'categoryId': 'cat_beverages',
    'price': 20.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_water',
    'name': 'Mineral Water',
    'description': 'Bottled drinking water',
    'categoryId': 'cat_beverages',
    'price': 20.0,
    'inStock': true,
    'imageUrl': '',
  },
  {
    'id': 'item_sting',
    'name': 'Sting',
    'description': 'Energy drink',
    'categoryId': 'cat_beverages',
    'price': 20.0,
    'inStock': true,
    'imageUrl': '',
  },
];